################################################################################
# 실행환경 - 운영
################################################################################
spring:
  profiles:
    include:
    - logging-file

config:
  shared:
    datasources:
      main:
        hikari:
          jdbc-url: "jdbc:mariadb://202.31.236.115:3306/jj_openapi"
          minimum-idle: 10
          maximum-pool-size: 500
    server-url: https://openapi.jj.ac.kr
    login:
      admin:
        ip-list:
        - "202.31.235.17"
        key: "U73yCz04P1UHcl3z12Qz5V633M3a2ocp5bqcXRTp4jhRSe7737"
        password: "4}.(@,'|6%:$^)0{,y7247L24c858-2[D;t=^-3s|(#_!--rD,"
    scheduler:
      enable: true
    email:
      test-email-address:
      onetime-send-count: 10
      sender-name: JavaMailSender
      sender-options:
        java-mail:
          session-properties:
            "mail.smtp.host": 127.0.0.1
            "mail.smtp.port": 25
            "mail.smtp.starttls.enable": false
            "mail.smtp.auth": false
          smtp-auth-username: ""
          smtp-auth-password: ""
