/*
 FusionCharts JavaScript Library jQuery Plugin
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
*/
FusionCharts.register("module",["private","HTMLTableDataHandler",function(){var q=this,z=q.window,E=z.document,h=function(f){var a,b,c=[];b=0;for(a=f.length;b<a;b+=1)3!==f[b].nodeType&&c.push(f[b]);return c},F=function(f){var a=h(f.childNodes);if(a.length){if("TBODY"===a[0].nodeName)return a[0];if("THEAD"===a[0].nodeName&&a[1]&&"TBODY"===a[1].nodeName)return a[1]}return f},v=function(f){return void 0!==f.innerText?f.innerText:f.textContent},C=function(f){var a,b,c,d,e,k,n=1,g,m={},p=[];a=0;for(c=
f.length;a<c;a+=1)for(e=h(f[a].childNodes),n=1,b=k=0,d=e.length;b<d;b+=1){g=b+n+k-1;m[g]&&a-m[g].rowNum<m[g].row&&(k+=m[g].col,g+=m[g].col);1<parseInt(e[b].getAttribute("rowspan"),10)&&(m[g]||(m[g]={}),m[g].rowNum=a,m[g].row=parseInt(e[b].getAttribute("rowspan"),10),1<parseInt(e[b].getAttribute("colspan"),10)?m[g].col=parseInt(e[b].getAttribute("colspan"),10):m[g].col=1);for(;p.length<=g;)p.push({childNodes:[]});p[g].childNodes.push(e[b]);1<parseInt(e[b].getAttribute("colspan"),10)&&(n+=parseInt(e[b].getAttribute("colspan"),
10)-1)}return p},D=function(f,a){for(var b=f.length;b;)if(b-=1,f[b]===a)return!0;return!1},t=0,x=function(f,a,b){var c,d,e,k,n=null,g=[],m=[],p=0,l,p={},q=0,w=0;if("undefined"===typeof b){k=h(f[0].childNodes);e=0;for(c=k.length;e<c;e+=1)if(f=e+q,g[f]="__fcBLANK__"+(f+1),l=parseInt(k[e].getAttribute("colspan"),10),l=1<l?l:parseInt(k[e].getAttribute("rowspan"),10),1<l){for(b=1;b<l;b+=1)g[f+b]="__fcBLANK__"+(f+b+1);q+=l-1}d=0;b=e+q;for(c=a.length;d<c;d+=1)0<a[d]?delete g[a[d]-1]:delete g[b+a[d]];return{index:-1,
labelObj:g}}if(0===b){d=0;for(b=f.length;d<b;d+=1){k=h(f[d].childNodes);e=p=m[d]=0;for(c=k.length;e<c;e+=1)if(!D(a,e+1)&&!D(a,e-c))if(l=v(k[e]),""===l.replace(/^\s*/,"").replace(/\s*$/,""))m[d]+=1;else if(parseFloat(l)!=l&&(p+=1,1<p))return x(f,a,d+1);0<d&&(m[d-1]>m[d]?n=d-1:m[d-1]<m[d]&&(n=d))}return null!==n?x(f,a,n+1):x(f,a)}0>b?b+=f.length:0<b&&(b-=1);k=h(f[b].childNodes);g=void 0!==f[0].nodeType?!0:!1;e=0;for(c=k.length;e<c;e+=1){n=0;g?"1"!==k[e].getAttribute("colspan")&&(n=parseInt(k[e].getAttribute("colspan"),
10)):"1"!==k[e].getAttribute("rowspan")&&(n=parseInt(k[e].getAttribute("rowspan"),10));n=1<n?n:0;l=v(k[e]);if(""!==l.replace(/^\s*/,"").replace(/\s*$/,""))p[e+w]=l;else{a:{q=C(f);d=b;var m=l=void 0,q=h(q[e].childNodes),u=void 0;l=0;for(m=q.length;l<m;l+=1)if(l!==d&&(u=v(q[l]),parseFloat(u)===u)){d=!0;break a}d=!1}d&&(p[e+w]="__fcBLANK__"+t,t+=1)}if(1<n){l=p[e+w];for(d=1;d<n;d+=1)p[e+w+d]=l+" ("+d+")";w+=n-1}}e=c+w;d=0;for(c=a.length;d<c;d+=1)0<a[d]?delete p[a[d]-1]:delete p[e+a[d]];return{labelObj:p,
index:b}};q.addDataHandler("HTMLTable",{encode:function(f,a,b){var c,d,e;a={chartAttributes:{},major:"row",useLabels:!0,useLegend:!0,labelSource:0,legendSource:0,ignoreCols:[],ignoreRows:[],showLabels:!0,showLegend:!0,seriesColors:[],convertBlankTo:"0",hideTable:!1,labels:[],legend:[],data:[]};var k,n,g,m={},p={};g=f;"string"===typeof g&&(g=E.getElementById(g));"undefined"!==typeof z.jQuery&&g instanceof z.jQuery&&(g=g.get(0));if(g){a.hideTable&&(g.style.display="none");var l,t,w,u;f={};var A,y,D,
B;d={};e={};var s;s=h(g.childNodes);s=s.length&&"THEAD"===s[0].nodeName&&s[1]&&"TBODY"===s[1].nodeName?s[0].childNodes:[];var G=h(s).concat(h(F(g).childNodes)),K=G.length,I=0,J=0,H=0,r=0;a.rowLabelSource=parseInt(a.labelSource,10);a.colLabelSource=parseInt(a.legendSource,10);g=a.useLabels?x(G,a.ignoreCols,a.rowLabelSource):x(G,a.ignoreCols);s=a.useLegend?x(C(G),a.ignoreRows,a.colLabelSource):x(C(G),a.ignoreRows);delete g.labelObj[s.index];delete s.labelObj[g.index];if("row"===a.major)for(l in s.labelObj)f[l]=
{};else for(l in g.labelObj)f[l]={};for(l=0;l<K;l+=1)if(g.index!==l&&void 0!==s.labelObj[l]){I+=1;w=h(G[l].childNodes);d[l]=0;e[l]={};t=H=0;for(D=w.length;t<D;t+=1){u=w[t];y=parseInt(u.getAttribute("colspan"),10);B=parseInt(u.getAttribute("rowspan"),10);for(A=t+d[l];r<l;){if(e[r])for(c in e[r]){if(c>A)break;l-r<=e[r][c].row&&(A+=e[r][c].col)}r+=1}1<y&&(d[l]+=y-1);1<B&&(e[l][A]=1<y?{row:B-1,col:y}:{row:B-1,col:1});if(s.index!==A&&void 0!==g.labelObj[A]){H+=1;u=v(u);if(""===u.replace(/^\s*/,"").replace(/\s*$/,
""))if(a.convertBlankTo)u=a.convertBlankTo;else continue;y=1<y?y:1;B=1<B?B:1;if("row"===a.major)for(r=0;r<y;){for(c=0;c<B;)f[l+c][A+r]=parseFloat(u),c+=1;r+=1}else for(r=0;r<y;){for(c=0;c<B;)f[A+r][l+c]=parseFloat(u),c+=1;r+=1}}}H>J&&(J=H)}c=1<I&&1<J?"multi":"single";d=s;e=g}else f=null,e=d=c=void 0;q.extend(a,b);"row"!==a.major?b=e:(b=d,d=e);m.chart=q.extend({},a.chartAttributes);if("multi"===c){m.categories=[{category:[]}];m.dataset=[];e=m.categories[0].category;g=m.dataset;c=0;for(k in f)for(n in!0===
a.showLabels?e.push(q.extend({label:"-1"!=b.labelObj[k].indexOf("__fcBLANK__")?"":b.labelObj[k]},a.labels[c])):e.push({label:""}),c+=1,f[k])"undefined"===typeof p[n]&&(p[n]=[]),p[n].push({value:f[k][n]});c=0;for(k in p)!0===a.showLegend?g.push(q.extend({seriesname:"-1"!==d.labelObj[k].indexOf("__fcBLANK__")?"":d.labelObj[k],data:p[k]},a.legend[c])):g.push({seriesname:"",data:p[k]}),c+=1}else if("single"===c)if(m.data=[],g=m.data,c=0,a.showLabels)for(k in f)for(n in f[k])g.push(q.extend({label:"-1"!==
b.labelObj[k].indexOf("__fcBLANK__")?"":b.labelObj[k],value:f[k][n]},a.labels[c])),c+=1;else for(k in f)for(n in f[k])g.push({value:f[k][n]});return{data:q.core.transcodeData(m,"JSON","XML"),error:void 0}},decode:function(f,a){q.raiseError(a,"07101734","run","::HTMLTableDataHandler.decode()","FusionCharts HTMLTable data-handler only supports decoding of data.");throw Error("FeatureNotSupportedException()");},transportable:!1})}]);
FusionCharts.register("module",["private","extensions.jQueryPlugin",function(){var q=this,z=q.window,E=z.document,h=z.jQuery,F,v,C,D=z.Math.min,t=q.hcLib.isArray,x={feed:"feedData",setdata:"setData",setdataforid:"setDataForId",getdata:"getData",getdataforid:"getDataForId",clear:"clearChart",stop:"stopUpdate",start:"restartUpdate"},f={feedData:function(a){return"string"===typeof a?[a]:"object"===typeof a&&a.stream?[a.stream]:!1},getData:function(a){return isNaN(a)?"object"===typeof a&&a.index?[a.index]:
[]:[a]},getDataForId:function(a){return"string"===typeof a?[a]:"object"===typeof a&&a.id?[a.id]:[]},setData:function(a,b,c){var d=[];"object"!==typeof a?d=[a,b,c]:(a.value&&d.push(a.value),a.label&&d.push(a.label));return d},setDataForId:function(a,b,c){var d=[];"string"===typeof a||"string"===typeof b||"string"===typeof c?d=[a,b,c]:"object"===typeof a&&(a.value&&d.push(a.value),a.label&&d.push(a.label));return d},clearChart:function(a){return[a]},stopUpdate:function(a){return[a]},restartUpdate:function(a){return[a]}};
h.FusionCharts=q.core;F=function(a,b){var c,d,e,k;d=t(b)||b instanceof h?D(a.length,b.length):a.length;for(c=0;c<d;c+=1)e=t(b)||b instanceof h?b[c]:b,a[c].parentNode?q.core.render(h.extend({},e,{renderAt:a[c]})):(e=new FusionCharts(h.extend({},e,{renderAt:a[c]})),h.FusionCharts.delayedRender||(h.FusionCharts.delayedRender={}),h.FusionCharts.delayedRender[e.id]=a[c],k=E.createElement("script"),k.setAttribute("type","text/javascript"),/msie/i.test(z.navigator.userAgent)&&!z.opera?k.text="FusionCharts.items['"+
e.id+"'].render();":k.appendChild(E.createTextNode("FusionCharts.items['"+e.id+"'].render()")),a[c].appendChild(k));return a};q.addEventListener("*",function(a,b){var c;h.extend(a,h.Event("fusioncharts"+a.eventType));a.sender&&a.sender.options?(c=a.sender.options.containerElement||a.sender.options.containerElementId,"object"===typeof c?h(c).trigger(a,b):h("#"+c).length?h("#"+c).trigger(a,b):h(E).trigger(a,b)):h(E).trigger(a,b)});v=function(a){return a.filter(":FusionCharts").add(a.find(":FusionCharts"))};
C=function(a,b,c){"object"===typeof b&&a.each(function(){this.configureLink(b,c)})};h.fn.insertFusionCharts=function(a){return F(this,a)};h.fn.appendFusionCharts=function(a){a.insertMode="append";return F(this,a)};h.fn.prependFusionCharts=function(a){a.insertMode="prepend";return F(this,a)};h.fn.attrFusionCharts=function(a,b){var c=[],d=v(this);if(void 0!==b)return d.each(function(){this.FusionCharts.setChartAttribute(a,b)}),this;if("object"===typeof a)return d.each(function(){this.FusionCharts.setChartAttribute(a)}),
this;d.each(function(){c.push(this.FusionCharts.getChartAttribute(a))});return c};h.fn.updateFusionCharts=function(a){var b={},c=v(this),d=[["swfUrl",!1],["type",!1],["height",!1],["width",!1],["containerBackgroundColor",!0],["containerBackgroundAlpha",!0],["dataFormat",!1],["dataSource",!1]],e,k,f,g,h,p;e=0;for(k=d.length;e<k;e+=1)h=d[e][0],b.type=b.type||b.swfUrl,a[h]&&(d[e][1]&&(g=!0),b[h]=a[h]);c.each(function(){f=this.FusionCharts;if(g)p=f.clone(b),p.render();else{if(void 0!==b.dataSource||void 0!==
b.dataFormat)void 0===b.dataSource?f.setChartData(f.args.dataSource,b.dataFormat):void 0===b.dataFormat?f.setChartData(b.dataSource,f.args.dataFormat):f.setChartData(b.dataSource,b.dataFormat);void 0===b.width&&void 0===b.height||f.resizeTo(b.width,b.height);b.type&&f.chartType(b.type)}});return this};h.fn.cloneFusionCharts=function(a,b){var c,d;"function"!==typeof a&&"function"===typeof b&&(d=a,a=b,b=d);c=[];v(this).each(function(){c.push(this.FusionCharts.clone(b,{},!0))});a.call(h(c),c);return this};
h.fn.disposeFusionCharts=function(){v(this).each(function(){this.FusionCharts.dispose();delete this.FusionCharts;0===this._fcDrillDownLevel&&delete this._fcDrillDownLevel});return this};h.fn.convertToFusionCharts=function(a,b){var c=[];"undefined"===typeof a.dataConfiguration&&(a.dataConfiguration={});h.extend(!0,a.dataConfiguration,b);a.dataSource||(a.dataSource=this.get(0));a.renderAt?"string"===typeof a.renderAt?c.push(h("#"+a.renderAt).insertFusionCharts(a).get(0)):"object"===typeof a.renderAt&&
c.push(h(a.renderAt).insertFusionCharts(a).get(0)):this.each(function(){c.push(h("<div></div>").insertBefore(this).insertFusionCharts(a).get(0))});return h(c)};h.fn.drillDownFusionChartsTo=function(){var a=v(this),b,c,d,e,f;"undefined"===typeof this._fcDrillDownLevel&&(this._fcDrillDownLevel=0);b=0;for(c=arguments.length;b<c;b+=1)if(f=arguments[b],t(f))for(d=0,e=f.length;d<e;d+=1)C(a,f[d],this._fcDrillDownLevel),this._fcDrillDownLevel+=1;else C(a,f,this._fcDrillDownLevel),this._fcDrillDownLevel+=
1;return this};h.fn.streamFusionChartsData=function(a,b,c,d){var e=v(this),k=[],h,g,m;g=x[a&&a.toLowerCase()];if(void 0===g)if(1===arguments.length)m=[a],g=x.feed;else return this;else m=1===arguments.length?[]:f[g](b,c,d);if("getData"===g||"getDataForId"===g)return e.each(function(){h=this.FusionCharts;"function"===typeof h[g]&&k.push(h[g].apply(h,m))}),k;e.each(function(){h=this.FusionCharts;"function"===typeof h[g]&&h[g].apply(h,m)});return this};h.extend(h.expr[":"],{FusionCharts:function(a){return a.FusionCharts instanceof
q.core}})}]);
