DROP VIEW IF EXISTS VW_SURVEY_QESTNR_CMMN_CODE;

CREATE VIEW VW_SURVEY_QESTNR_CMMN_CODE AS
SELECT VSQC.SURVEY_QESTNR_ID
     , VSQC.SURVEY_DIV
     , VSQC.SURVEY_CODE
     , VSQC.CODE_GROUP
     , VSQC.CODE_TITLE
     , TSCV.CODE_VALUE
     , TSCV.CODE_VALUE_NM
     , VSQC.SORT_ORDR AS SORT_ORDR1
     , TSCV.SORT_ORDR AS SORT_ORDR2
FROM   VW_SURVEY_QESTNR_CMMN VSQC
       LEFT JOIN TB_SYS_CODE_GROUP TSCG ON TSCG.CODE_GROUP = VSQC.CODE_GROUP
       LEFT JOIN TB_SYS_CODE_VALUE TSCV ON TSCV.CODE_GROUP_ID = TSCG.CODE_GROUP_ID
;
