DROP VIEW IF EXISTS VW_PERSON_SURVEY_QESTNR;

CREATE VIEW VW_PERSON_SURVEY_QESTNR AS
-- 본인이 작성한 건
SELECT TSQ.REGIST_PSN_ID AS PERSON_ID
     , TSQ.SURVEY_QESTNR_ID
FROM   TB_SURVEY_QESTNR TSQ
UNION
-- 전체 공유인 건
SELECT TCP.PERSON_ID
     , TSQ.SURVEY_QESTNR_ID
FROM   TB_SURVEY_QESTNR TSQ
       INNER JOIN TB_COM_PERSON TCP ON 1 = 1
WHERE  TSQ.CNRS_YN = 'A'
UNION
-- 부서 공유인 건
SELECT TCP.PERSON_ID
     , TSQ.SURVEY_QESTNR_ID
FROM   TB_SURVEY_QESTNR TSQ
       INNER JOIN TB_COM_PERSON_DEPT TCPD ON TCPD.DEPT_ID = TSQ.REGIST_DEPT_ID
       INNER JOIN TB_COM_PERSON TCP ON TCP.PERSON_ID = TCPD.PERSON_ID
WHERE  TSQ.CNRS_YN = 'D'
;
