DROP VIEW IF EXISTS VW_PERSON_SURVEY_GROUP;

CREATE VIEW VW_PERSON_SURVEY_GROUP AS
-- 본인이 작성한 건
SELECT TSG.REGIST_PSN_ID AS PERSON_ID
     , TSG.SURVEY_GROUP_ID
FROM   TB_SURVEY_GROUP TSG
UNION
-- 전체 공유인 건
SELECT TCP.PERSON_ID
     , TSG.SURVEY_GROUP_ID
FROM   TB_SURVEY_GROUP TSG
       INNER JOIN TB_COM_PERSON TCP ON 1 = 1
WHERE  TSG.CNRS_YN = 'A'
UNION
-- 부서 공유인 건
SELECT TCP.PERSON_ID
     , TSG.SURVEY_GROUP_ID
FROM   TB_SURVEY_GROUP TSG
       INNER JOIN TB_COM_PERSON_DEPT TCPD ON TCPD.DEPT_ID = TSG.REGIST_DEPT_ID
       INNER JOIN TB_COM_PERSON TCP ON TCP.PERSON_ID = TCPD.PERSON_ID
WHERE  TSG.CNRS_YN = 'D'
;
